CREATE TABLE IF NOT EXISTS "Users"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Username" varchar(50) NOT NULL,
    "PasswordHash" varchar(500) NOT NULL,
    "Email" varchar(254) NOT NULL,
    "Age" integer NOT NULL,
    "Gender" varchar(30) NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    "UpdatedAtUtc" timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Users_Age" CHECK ("Age" BETWEEN 1 AND 130)
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Users_Username" ON "Users" ("Username");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Users_Email" ON "Users" ("Email");
